on: [push, pull_request]

name: Tests

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Linter
        run: npx eslint .
      - name: Run the tests
        run: npm test